version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  show-stats: false
  formats:
    text:
      colors: true
      print-issued-lines: true
      print-linter-name: true

linters:
  default: none
  enable:
    # Core linters compatible with golangci-lint v2
    - errcheck      # Check for unchecked errors
    - govet         # Go vet
    - ineffassign   # Detect ineffectual assignments
    - misspell      # Check spelling
    - revive        # Drop-in replacement for golint
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Check for unused function parameters
    - gocritic      # Go critic
    - gocyclo       # Check cyclomatic complexity
    - dupl          # Check for duplicated code
    - gosec         # Security checker
    - prealloc      # Find slice declarations with non-zero initial length

  settings:
    gocyclo:
      min-complexity: 15

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - unnamedResult
        - hugeParam

    revive:
      rules:
        - name: var-naming
        - name: package-comments
        - name: exported
        - name: var-declaration
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: increment-decrement
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf

    gosec:
      excludes:
        - G404 # Insecure random number source (rand)

  exclusions:
    presets: []
    paths: []
    generated: lax
    rules:
      # Exclude some linters from running on tests files
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - gocritic

      # Exclude linters from running on examples (demo code)
      - path: examples/
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gocritic
          - gosec
          - revive
          - unparam

      # Exclude known linters from generated files
      - path: ".*\\.pb\\.go"
        linters:
          - revive
          - stylecheck

      # Accept high complexity in type coercion functions - inherent to comprehensive type handling
      - text: "func `(coerce(To(Int|Uint|Float|String)|parseTime)|toInt)`"
        linters:
          - gocyclo

      # Accept complexity in comprehensive validators
      - text: "func `.*Validate`"
        linters:
          - gocyclo

      # Accept complexity in ParseIntoWithFormat - inherent to main parsing logic
      - text: "func `ParseIntoWithFormat`"
        linters:
          - gocyclo

      # Accept duplication between Min/Max validators - expected pattern
      - path: pkg/model/validators\.go
        text: "lines are duplicate"
        linters:
          - dupl

      # Accept unused error returns for future API extensibility
      - text: "result .* is always nil"
        linters:
          - unparam

      # Exclude common false positives
      - text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
        linters:
          - errcheck

issues:
  max-same-issues: 0
  uniq-by-line: true
